In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
#2D array
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
#3D array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [25]:
#here 1,15 is the range means give me 3 numbers having values between 1-15
np.random.randint(1,15,3)

array([9, 7, 8])

In [26]:
#3*3 arraywith random ints between 0-9
#np.random.randint(15,size=(3,3))
np.random.randint(25,size=(4,4))

array([[10, 14, 12,  6],
       [ 1, 23, 16,  2],
       [12,  0,  6, 18],
       [22, 12, 21, 10]])

In [23]:
#bool datatype
np.array([1,2,3,0,5],dtype=bool)

array([ True,  True,  True, False,  True])

In [24]:
#7*7 array of 0 and 1 in diagonal Identity Matrix
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [27]:
#Array of values from 0 to less than 15 with step 3
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [28]:
from numpy import*
a=arange(12)
a=a.reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [29]:
trans=np.array([(1,2,3,4),(5,6,7,8)])
trans.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
trans.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [31]:
#Changes arr shape to 6*6 and fills new values with 0
trans.resize((6,6), refcheck=False)
trans

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [32]:
#returns number of elements in arr
arr= np.array([1,2,3,4,6,7,9])
arr.size

7

In [33]:
#Appends values to end of arr
arr2=np.append(arr,[0,1,2,3,4,5])
arr2

array([1, 2, 3, 4, 6, 7, 9, 0, 1, 2, 3, 4, 5])

In [34]:
#insert values into arr before index 2
np.insert(arr2,2,4)

array([1, 2, 4, 3, 4, 6, 7, 9, 0, 1, 2, 3, 4, 5])

In [35]:
#delete row on index 4 of arr
np.delete(trans,4)

array([1, 2, 3, 4, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
#deletes column on index 5 of arr
np.delete(trans,5,axis=1)

array([[1, 2, 3, 4, 5],
       [7, 8, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
abs(-1)

1

In [38]:
add.accumulate(array([1.,2.,3.,4.]))

array([ 1.,  3.,  6., 10.])

In [39]:
multiply.accumulate(array([1.,2.,3.,4.]))

array([ 1.,  2.,  6., 24.])

In [40]:
add.accumulate(array([[1,2,3],[4,5,6]]),axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [41]:
add(array([-1.2,1.2]), array([1,3]))

array([-0.2,  4.2])

In [42]:
array([-1.2,1.2])+array([1,3])

array([-0.2,  4.2])

In [43]:
a= array([True,False,True])
a.all()

False

In [44]:
allclose(array([1e10,1e-7]), array([1.00001e10,1e-8]))

False

In [45]:
#in radians
angle(1+1j)

0.7853981633974483

In [46]:
#in degrees
angle(1+1j,deg=True)

45.0

In [48]:
a=array([True, False, True])
a.any()

True

In [49]:
from numpy import*
a=array([10,20,30,40])
append(a,50)

array([10, 20, 30, 40, 50])

In [50]:
array([10, 20, 30, 40, 50])
append(a,[50,60])

array([10, 20, 30, 40, 50, 60])

In [51]:
array([10, 20, 30, 40, 50])
append(a,[59,60])

array([10, 20, 30, 40, 59, 60])

In [52]:
#view documentation for arr.tolist
np.info(arr.tolist)

a.tolist()

Return the array as an ``a.ndim``-levels deep nested list of Python scalars.

Return a copy of the array data as a (nested) Python list.
Data items are converted to the nearest compatible builtin Python type, via
the `~numpy.ndarray.item` function.

If ``a.ndim`` is 0, then since the depth of the nested list is 0, it will
not be a list at all, but a simple Python scalar.

Parameters
----------
none

Returns
-------
y : object, or list of object, or list of list of object, or ...
    The possibly nested list of array elements.

Notes
-----
The array may be recreated via ``a = np.array(a.tolist())``, although this
may sometimes lose precision.

Examples
--------
For a 1D array, ``a.tolist()`` is almost the same as ``list(a)``,
except that ``tolist`` changes numpy scalars to Python scalars:

>>> a = np.uint32([1, 2])
>>> a_list = list(a)
>>> a_list
[1, 2]
>>> type(a_list[0])
<class 'numpy.uint32'>
>>> a_tolist = a.tolist()
>>> a_tolist
[1, 2]
>>> type(a_tolist[0])
<class 'int'

In [54]:
from numpy import *
def myfun(a): #fun works on a 1 D arrays, takes the average of the 1st and the last element
    return(a[0]+a[-1])/2
b=array([[1,2,3],[4,5,6],[7,8,9]])
apply_along_axis(myfun,0,b)

array([4., 5., 6.])

In [1]:
from numpy import*
a=arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [2]:
#sum over all axes except axis=1, result has same shape as original
apply_over_axes(sum, a,[0,2])

array([[[ 60],
        [ 92],
        [124]]])

In [3]:
from numpy import*
arange(5)

array([0, 1, 2, 3, 4])

In [4]:
arange((5.0))

array([0., 1., 2., 3., 4.])

In [5]:
from numpy import *
arccos(array([0,1]))

array([1.57079633, 0.        ])

In [8]:
arccosh(array([e,10.0]))

array([1.65745445, 2.99322285])

In [9]:
arcsin(array([0,1]))

array([0.        , 1.57079633])

In [10]:
arcsinh(array([e,10.0]))

array([1.72538256, 2.99822295])

In [11]:
arctan(array([0,1]))

array([0.        , 0.78539816])

In [12]:
arctan2(array([0,1]),array([1,0]))

array([0.        , 1.57079633])

In [13]:
arctanh(array([0,-0.5]))

array([ 0.        , -0.54930614])

In [14]:
from numpy import *
a=array([10,20,30])
maxindex=a.argmax()
a[maxindex]

30

In [16]:
a=array([[10,20,30],[40,70,90]])
maxindex=a.argmax()
maxindex

5

In [17]:
a.ravel()[maxindex]

90

In [19]:
#for each column: the row index of the maximum value
a.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [20]:
#for each row: the column index of the maximum value
a.argmax(axis=1)

array([2, 2], dtype=int64)

In [21]:
#also exists, slower, default is axis=-1
argmin(a)

0

In [22]:
from numpy import *
a= array([2,0,8,4,1])
a

array([2, 0, 8, 4, 1])

In [23]:
#indices of sorted array using quicksort(default)
ind=a.argsort()
ind

array([1, 4, 0, 3, 2], dtype=int64)

In [24]:
#same as a.sort()
a[ind]

array([0, 1, 2, 4, 8])

In [28]:
ind=a.argsort(kind='merge')
a=array([[8,4,1],[2,0,9]])
ind=a.argsort(axis=0) #sorts on cloumns. NOT the same as a.sort(axis=1)
ind

array([[1, 1, 0],
       [0, 0, 1]], dtype=int64)

In [27]:
from numpy import*
abs(-1)

1

In [29]:
abs(array([-1.2,1.2]))

array([1.2, 1.2])

In [30]:
abs(1.2+1j)

1.5620499351813308

In [32]:
#like reduce() but also gives intermediate results
from numpy import *
add.accumulate(array([1.,2.,3.,4.]))

array([ 1.,  3.,  6., 10.])

In [33]:
#works also with other operands
multiply.accumulate(array([1.,2.,3.,4.]))

array([ 1.,  2.,  6., 24.])

In [35]:
#Array of 5 evenly divided values from 0 to 150
import numpy as np
np.linspace(0,150,5)

array([  0. ,  37.5,  75. , 112.5, 150. ])

In [37]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr.size

9

In [38]:
#returns dimensions of arr(rows,columns)
arr.shape

(9,)

In [39]:
#convert arr to a python list
arr.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
#copies arr to new memory
np.copy(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#sorts arr
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#sorts specific axis of arr
arr.sort(axis=0)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#appends value to the end of arr
arr2=np.append(arr,[0,1,2,4,5])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 4, 5])

In [44]:
np.concatenate((arr,arr2),axis=0)#adds arr2 as rows to the end of arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 4,
       5])

In [45]:
#adds arr2 as columns to end of arr1
trans=np.array([(1,2,3,4),(5,6,7,8)])
np.concatenate((trans,trans), axis=1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])